import type { MetadataRoute } from 'next';

/**
 * Web App Manifest — generated by Next 15 at /manifest.webmanifest.
 *
 * Configures HIBI 45 as a standalone PWA. Adding to home screen on iOS
 * or Android opens the app full-screen, without browser chrome — same
 * envelope as a native app, same monochrome envelope as the web.
 *
 * No service worker yet (no offline). The manifest is enough for the
 * "feels like an app" experience the user asked for; offline support
 * is its own concern (would need cache strategies, optimistic write
 * queues, conflict resolution against Supabase). V1 stays online-only.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: 'HIBI 45 — 日々',
    short_name: 'HIBI 45',
    description:
      'Forty-five days. Five practices each day. Miss one, and the path begins again.',
    start_url: '/today',
    scope: '/',
    display: 'standalone',
    orientation: 'portrait',
    background_color: '#0a0a0a',
    theme_color: '#0a0a0a',
    lang: 'en',
    categories: ['lifestyle', 'health', 'productivity'],
    // Single SVG icon serves all sizes on Android/Chrome. iOS doesn't read
    // the manifest's icons; it uses /apple-icon (generated by app/apple-icon.tsx).
    // Both routes are produced at request time by Next's ImageResponse — no
    // PNG binaries to commit or maintain.
    icons: [{ src: '/icon', sizes: 'any', type: 'image/png' }],
  };
}
